### ISSUE TITLE
Unresolved dependencies io.kamon#kamon-core_2.11;0.6.0

### ISSUE THREAD

**Issue by sadziu** [pawelkaczor/ddd-leaven-akka-v2#13]
Hi, 
I try to build master branch
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: io.kamon#kamon-core_2.11;0.6.0-a9d5c5c61f7e5e189bf67baee2b13e21ebbaaf73: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          io.kamon:kamon-core_2.11:0.6.0-a9d5c5c61f7e5e189bf67baee2b13e21ebbaaf73
[warn]            +- pl.newicom.dddd:akka-ddd-monitoring_2.11:1.1.0-SNAPSHOT (D:\akka\ddd-leaven-akka-v2\sales\build.sbt#L19)
[warn]            +- pl.newicom:sales-write-back_2.11:0.2.4-SNAPSHOT
[info] Wrote D:\akka\ddd-leaven-akka-v2\shipping\write-back\target\scala-2.11\shipping-write-back_2.11-0.2.4-SNAPSHOT.pom
[info] Wrote D:\akka\ddd-leaven-akka-v2\sales\read-front\target\scala-2.11\sales-read-front_2.11-0.2.4-SNAPSHOT.pom
[info] Wrote D:\akka\ddd-leaven-akka-v2\shipping\read-back\target\scala-2.11\shipping-read-back_2.11-0.2.4-SNAPSHOT.pom
[info] Wrote D:\akka\ddd-leaven-akka-v2\sales\contracts\target\scala-2.11\sales-contracts_2.11-0.2.4-SNAPSHOT.pom
[info] Wrote D:\akka\ddd-leaven-akka-v2\shipping\read-front\target\scala-2.11\shipping-read-front_2.11-0.2.4-SNAPSHOT.pom
[info] Wrote D:\akka\ddd-leaven-akka-v2\commons\target\scala-2.11\commons_2.11-0.2.4-SNAPSHOT.pom
[info] Wrote D:\akka\ddd-leaven-akka-v2\invoicing\contracts\target\scala-2.11\invoicing-contracts_2.11-0.2.4-SNAPSHOT.pom
[info] Wrote D:\akka\ddd-leaven-akka-v2\shipping\contracts\target\scala-2.11\shipping-contracts_2.11-0.2.4-SNAPSHOT.pom
sbt.ResolveException: unresolved dependency: io.kamon#kamon-core_2.11;0.6.0-a9d5c5c61f7e5e189bf67baee2b13e21ebbaaf73: not found

**Comment by sadziu** [comment]
sbt update solved this problem

**Comment by pawelkaczor** [comment]
Ok. Thanks for reporting anyway.

2016-02-12 10:34 GMT+01:00, Paweł Sadowski <notifications@github.com>:
> Closed #13.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pawelkaczor/ddd-leaven-akka-v2/issues/13#event-548300694


-- 
Pozdrawiam
Paweł Kaczor
