### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by manelephant** [pawelkaczor/ddd-leaven-akka-v2#15]
Does anybody has seen this message : 

    Read from stdout: (sales-contracts/*:update) sbt.ResolveException: unresolved dependency: pl.newicom.dddd#akka-ddd-messaging_2.11;1.2.1-SNAPSHOT: not found

**Comment by pawelkaczor** [comment]
Are you building the current version of ddd-leaven-akka-v2 (that uses akka-ddd 1.2.2-SNAPSHOT) ?

**Comment by manelephant** [comment]
Sorry for the late response - i finally managed to make it work 👍
