### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/ddd-leaven-akka-v2#2]
![screen shot 2015-05-09 at 13 22 22](https://cloud.githubusercontent.com/assets/930785/7549980/7bdd9838-f64e-11e4-812f-1559394056c9.png)
did a pull of the project but i cannot compile it.  It is complaining that the contract dependencies are missing

**Comment by pawelkaczor** [comment]
Fixed. Thanks for reporting.
