### ISSUE TITLE
 Can't run!  Resolution failed several times for dependency: com.typesafe.sbt#sbt-native-packager;1.2.2-RC2 

### ISSUE THREAD

**Issue by liaolunhui** [pawelkaczor/ddd-leaven-akka-v2#23]
![image](https://user-images.githubusercontent.com/13741751/37906117-a74f5146-3133-11e8-8ba8-49bf94f79ec6.png)

dev@lhh:~/ddd-leaven-akka-v2$ sbt stage
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/dev/ddd-leaven-akka-v2/project
[info] Updating {file:/home/dev/ddd-leaven-akka-v2/project/}ddd-leaven-akka-v2-build...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-native-packager;1.2.2-RC2: Resolution failed several times for dependency: com.typesafe.sbt#sbt-native-packager;1.2.2-RC2 {compile=[default(compile)]}::
[warn]  1
[warn]  1
[warn]  1
[warn]  :: io.get-coursier#sbt-coursier;1.0.0-RC13: Resolution failed several times for dependency: io.get-coursier#sbt-coursier;1.0.0-RC13 {compile=[default(compile)]}::
[warn]  1
[warn]  1
[warn]  1
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbt:sbt-native-packager:1.2.2-RC2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          io.get-coursier:sbt-coursier:1.0.0-RC13 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.sbt:sbt-native-packager:1.2.2-RC2 (scalaVersion=2.12, sbtVersion=1.0) (/home/dev/ddd-leaven-akka-v2/project/plugins.sbt#L1-2)
[warn]            +- default:ddd-leaven-akka-v2-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          io.get-coursier:sbt-coursier:1.0.0-RC13 (scalaVersion=2.12, sbtVersion=1.0) (/home/dev/ddd-leaven-akka-v2/project/plugins.sbt#L3-4)
[warn]            +- default:ddd-leaven-akka-v2-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.2.2-RC2: Resolution failed several times for dependency: com.typesafe.sbt#sbt-native-packager;1.2.2-RC2 {compile=[default(compile)]}::
[error]         1
[error]         1
[error]         1
[error]
[error] unresolved dependency: io.get-coursier#sbt-coursier;1.0.0-RC13: Resolution failed several times for dependency: io.get-coursier#sbt-coursier;1.0.0-RC13 {compile=[default(compile)]}::
[error]         1
[error]         1
[error]         1
[error]
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[error]         at java.base/java.lang.Thread.run(Thread.java:844)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.2.2-RC2: Resolution failed several times for dependency: com.typesafe.sbt#sbt-native-packager;1.2.2-RC2 {compile=[default(compile)]}::
[error]         1
[error]         1
[error]         1
[error]
[error] unresolved dependency: io.get-coursier#sbt-coursier;1.0.0-RC13: Resolution failed several times for dependency: io.get-coursier#sbt-coursier;1.0.0-RC13 {compile=[default(compile)]}::
[error]         1
[error]         1
[error]         1
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by pawelkaczor** [comment]
@liaolunhui Thanks for reporting.
