### ISSUE TITLE
Implement application main classes (get rid of akka microkernel)

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/ddd-leaven-akka-v2#3]
There is a specific reason to use bootable?    To debut the code in the ide in a easy way i added the following but using app without bootable will be better. 

//code to start in a ide friendly way 
package ecommerce.sales.app
object SalesBackendMain extends App{
  val starter = new SalesBackendApp()
  starter.startup()
}

**Comment by pawelkaczor** [comment]
+1 (Bootable is deprecated)

**Comment by albertolobrano** [comment]
I will send you a pull request shortly

**Comment by albertolobrano** [comment]
Let me know if that would work and i will do the others

**Comment by pawelkaczor** [comment]
Looks good to me but I would consider introducing new module (commons) and putting there logic of application startup/shutdown (log messages, maybe other responsibilities in the future) that can be reused by all applications. What do you think?

**Comment by pawelkaczor** [comment]
One more thing. mainClass in build.sbt needs to be changed. More information here: http://doc.akka.io/docs/akka/snapshot/intro/deployment-scenarios.html

**Comment by albertolobrano** [comment]
ok make sense . I will do in the weekend

**Comment by pawelkaczor** [comment]
commons module added with akka.Main (copied from akka sources)
