### ISSUE TITLE
Create a monolith version  for development purposes and small deployemnt

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/ddd-leaven-akka-v2#4]
right now we have an application that is a collection of micro services which is very good and i like it a lot. 

Without loosing this feature we should be able to compose each microservice and run the application as monolith. It can be good for development purposes or for small deployments.  With a monolith debugging the app will be very easy.

The idea is to have a subproject that is able to start all the micro services as one application.

**Comment by pawelkaczor** [comment]
Will you be able to describe initial design of such monolithic system?

Please not that currently you can start whole system with just one command: vagrant up (executed in e2e-tests folder). I will update Readme asap.

**Comment by albertolobrano** [comment]
I thought about this and it adds too much complexity for an example project.  In my project instead to have every micro service in its own package i implemented under 1 package and created several offices.

we can close this for now.
