### ISSUE TITLE
AR - Service collaboration

### ISSUE THREAD

**Issue by albertolobrano** [pawelkaczor/ddd-leaven-akka-v2#5]
Right now we have aggregates roots and process manager but we do not have any service.   Have you thought about it ?

**Comment by pawelkaczor** [comment]
This is a good question. I have thought about it (AR - Service collaboration) and found solution. But first we need to think of an example service that could be added to the our app. Any idea?

**Comment by albertolobrano** [comment]
what about sequence number generator?   It is common  to identify the business object like orders, payment, invoices with a unique sequential number and some time can have prefixes and suffixes too.

Right now we identify the aggregates (order) with the UUID which is fine for a computer system but not usable from a person.  Think if you want to complain because your order is late and you need to communicate the UUID over the phone :)  is too much.   

Let's say we have an office (persistent actor ) that is able to generate the numbers for us  and we want to expose it as a service.   So when we create a sale or a shipping we call the domain service for the sequence number and we attach it to the aggregate. 


would this fit with a domain service ?

**Comment by pawelkaczor** [comment]
Excellent idea :+1: But I don't see a reason to model this service as normal office. For now I would prefer to model the service as simple, not persistent actor. Later we can think of incorporating (https://github.com/jboner/akka-crdt)[akka-crdt) if that makes sense. 

I will start working on this soon.

**Comment by albertolobrano** [comment]
because it will make explicit the collaboration of multiple aggregates.   

i need an id   i walk to the office i request one. the offices will use whatever logic and then i pass it to my office

**Comment by pawelkaczor** [comment]
Collaboration of multiple aggregates constitutes a business process which
must be managed by Saga. AR must not communicate directly with other AR as
this would break AR transaction boundary.

2015-05-15 10:31 GMT+02:00 Alberto Lobrano <notifications@github.com>:

**Comment by albertolobrano** [comment]
Ok got it.  i am curious to see your code.  I will also need this for my project and generation of sequence number that is super easy in traditional system is kind of difficult  in cqrs.  

For the invoice number i am thinking to solved it in this way.

1) create the invoice  with the UUID and with status created and a provisional invoice number. 
2) When the user approves the invoice the approvedInvoice event will be received by  a Process Manager (SAGA) that will issue an id (in europe the invoices must have sequence number, restarted every year with no gaps.)  and will send the  command  AddInvoiceProtocolNumber to the invoice 

3) in the front end i will wait for the protocol number to be set before returning the response for ApproveInvoice. 

---------

**Comment by pawelkaczor** [comment]
Take a look: https://github.com/pawelkaczor/akka-ddd/commit/4bb69eacb1cfe2ec108fbc2980e58e1da9a85bd0

**Comment by pawelkaczor** [comment]
>> 2) When the user approves the invoice the approvedInvoice event will be received by a Process Manager (SAGA) that will issue an id (in europe the invoices must have sequence number, restarted every year with no gaps.) and will send the command AddInvoiceProtocolNumber to the invoice

Sounds good as long as invoice number once generated (by external service, as I understand) will eventually reach Saga.

**Comment by pawelkaczor** [comment]
Closing although example has not been implemented.
