### ISSUE TITLE
Compilation error in e2e-tests

### ISSUE THREAD

**Issue by sadziu** [pawelkaczor/ddd-leaven-akka-v2#6]
I did pull and now try to import it to Intellij
<code/>
[warn] 	Note: Unresolved dependencies path:
[warn] 		pl.newicom:resttest_2.11:0.2.0-SNAPSHOT (C:\kod\ddd-leaven-akka-v2\e2e-tests\build.sbt#L10)
[warn] 		  +- pl.newicom:e2e-tests_2.11:0.1-M2
[trace] Stack trace suppressed: run 'last e2e-tests/*:update' for the full output.
[error] (e2e-tests/*:update) sbt.ResolveException: unresolved dependency: pl.newicom#resttest_2.11;0.2.0-SNAPSHOT: not found
sbt.ResolveException: unresolved dependency: pl.newicom#resttest_2.11;0.2.0-SNAPSHOT: not found
<code/>

**Comment by pawelkaczor** [comment]
Ok, will fix soon. Thanks for reporting.
