### ISSUE TITLE
Compilation error in e2e-tests - play-json

### ISSUE THREAD

**Issue by sadziu** [pawelkaczor/ddd-leaven-akka-v2#7]
After [this](https://github.com/pawelkaczor/ddd-leaven-akka-v2/issues/6) fix there is another one unresolved dependency
<code>
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:play-json_2.11:2.3.4
[warn] 		  +- pl.newicom:resttest_2.11:0.2.0 (C:\kod\ddd-leaven-akka-v2\e2e-tests\build.sbt#L10)
[warn] 		  +- pl.newicom:e2e-tests_2.11:0.1-M2
[trace] Stack trace suppressed: run 'last e2e-tests/*:update' for the full output.
[error] (e2e-tests/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#play-json_2.11;2.3.4: not found
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-json_2.11;2.3.4: not found
<code/>

**Comment by sadziu** [comment]
resttest 0.2.0 has dependency to it
<code>
<module organisation="com.typesafe.play" name="play-json_2.11">
			<revision name="2.3.4" error="not found" downloaded="false" searched="false" conf="compile(*), runtime(*), master(compile)" position="-1">
				<caller organisation="pl.newicom" name="resttest_2.11" conf="default, compile, runtime, master" rev="2.3.4" rev-constraint-default="2.3.4" rev-constraint-dynamic="2.3.4" callerrev="0.2.0"/>
				<artifacts>
				</artifacts>
			</revision>
		</module>
</code>
and there is no play-json 2.3.4 in maven-repository

**Comment by pawelkaczor** [comment]
Yes, I'm fixing this now.

2015-06-03 11:57 GMT+02:00, Paweł Sadowski <notifications@github.com>:
> resttest 0.2.0 has dependency to it
> <code>
> <module organisation="com.typesafe.play" name="play-json_2.11">
> 			<revision name="2.3.4" error="not found" downloaded="false"
> searched="false" conf="compile(*), runtime(*), master(compile)"
> position="-1">
> 				<caller organisation="pl.newicom" name="resttest_2.11" conf="default,
> compile, runtime, master" rev="2.3.4" rev-constraint-default="2.3.4"
> rev-constraint-dynamic="2.3.4" callerrev="0.2.0"/>
> 				<artifacts>
> 				</artifacts>
> 			</revision>
> 		</module>
> </code>
> and there is no play-json 2.3.4 in maven-repository
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pawelkaczor/ddd-leaven-akka-v2/issues/7#issuecomment-108283538


-- 
Pozdrawiam
Paweł Kaczor

**Comment by pawelkaczor** [comment]
Should be ok now.
