### ISSUE TITLE
sbt error

### ISSUE THREAD

**Issue by ajaychandran** [pawelkaczor/ddd-leaven-akka-v2#8]
Looks like the `jersey` dependency version is not being resolved.

[warn] ==== Akka Snapshot Repository: tried
[warn]   http://repo.akka.io/snapshots/com/sun/jersey/jersey-client/[revision]/jersey-client-[revision].pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.sun.jersey#jersey-core;[1.17,1.18): not found
[warn] 	:: com.sun.jersey#jersey-client;[1.17,1.18): not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.sun.jersey:jersey-core:[1.17,1.18)
[warn] 		  +- pl.newicom:resttest_2.11:0.3.0-SNAPSHOT (/home/ajay/activator/workspace/ddd-leaven-akka-v2/e2e-tests/build.sbt#L10)
[warn] 		  +- pl.newicom:e2e-tests_2.11:0.1-M2
[warn] 		com.sun.jersey:jersey-client:[1.17,1.18)
[warn] 		  +- pl.newicom:resttest_2.11:0.3.0-SNAPSHOT (/home/ajay/activator/workspace/ddd-leaven-akka-v2/e2e-tests/build.sbt#L10)
[warn] 		  +- pl.newicom:e2e-tests_2.11:0.1-M2

**Comment by pawelkaczor** [comment]
Fixed: https://github.com/pawelkaczor/resttest/commit/e1d893e8fff420b12c8d9af7eda54cc40e025308

**Comment by pistotniks** [comment]
When I try to build it with typesafe activator, it cannot build; I get:

Read from stdout: (e2e-tests/*:update) sbt.ResolveException: unresolved dependency: pl.newicom#resttest_2.11;0.3.0-SNAPSHOT: not found
(e2e-tests/*:update) sbt.ResolveException: unresolved dependency: pl.newicom#resttest_2.11;0.3.0-SNAPSHOT: not found

**Comment by pawelkaczor** [comment]
Thanks @pistotniks for reporting the error. It is fixed now (https://github.com/pawelkaczor/ddd-leaven-akka-v2/commit/d1a7fc46e1b6a558462fb1e6f2e8b9a424d7e4b5)
