### ISSUE TITLE
Write-Front fails to connect to Write-Back

### ISSUE THREAD

**Issue by stuartsaltzman** [pawelkaczor/ddd-leaven-akka-v2#9]
Hi, 

I am unable to run your e2e tests or the manual tests. I follow the manual test steps then execute the http POST to create a reservation and it fails (log messages are below). Looking at the logs (via vagrant docker-logs) I see many number of the following warnings messages:

*==> sales-write-front: 17:39:52.841UTC WARN  akka.tcp://sales-front@127.0.1.1:50880/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fsales%40127.0.0.1%3A9101-0 - Association with remote system [akka.tcp://sales@127.0.0.1:9101] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://sales@127.0.0.1:9101]] Caused by: [Connection refused: /127.0.0.1:9101]*

The error message from executing the http POST (http :9100/ecommerce/sales Command-Type:ecommerce.sales.CreateReservation reservationId="r1" customerId="customer-1") is below:

*==> sales-write-front: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://sales-front/user/$a#641128582]] after [3000 ms]. Sender[Actor[akka://sales-front/user/sales-front-supervisor/http-service#-1858549503]] sent message of type "pl.newicom.dddd.messaging.command.CommandMessage".
==> sales-write-front: 	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:415) ~[com.typesafe.akka.akka-actor_2.11-2.4-M1.jar:na]
==> sales-write-front: 	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:127) ~[com.typesafe.akka.akka-actor_2.11-2.4-M1.jar:na]
==> sales-write-front: 	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599) ~[org.scala-lang.scala-library-2.11.6.jar:na]
==> sales-write-front: 	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[org.scala-lang.scala-library-2.11.6.jar:na]
==> sales-write-front: 	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597) ~[org.scala-lang.scala-library-2.11.6.jar:na]
==> sales-write-front: 	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:477) ~[com.typesafe.akka.akka-actor_2.11-2.4-M1.jar:na]
==> sales-write-front: 	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:429) ~[com.typesafe.akka.akka-actor_2.11-2.4-M1.jar:na]
==> sales-write-front: 	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:433) ~[com.typesafe.akka.akka-actor_2.11-2.4-M1.jar:na]
==> sales-write-front: 	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:385) ~[com.typesafe.akka.akka-actor_2.11-2.4-M1.jar:na]
==> sales-write-front: 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66-internal]
==> sales-write-front: 17:40:43.756UTC DEBUG akka://sales-front/system/IO-TCP/selectors/$a/9 - unhandled message from Actor[akka://sales-front/system/IO-TCP-STREAM/server-1-%2F0.0.0.0%3A9100/$i#1289120453]: ResumeReading*

Thanks for this great Akka CQRS/DDDD example! And thank you in advance your help!

**Comment by pawelkaczor** [comment]
I checked now and the test works on my machine. Please provide log of write-back subsystem. Please check if docker container of write-back is running.

**Comment by stuartsaltzman** [comment]
I changed the base docker image within project/CommonDockerSettingsPlugin.scala to "java:8" because I get an error that "dockerfile/java:oracle-java8" is not found when running the e2e:test within sbt console (error below). 

sales-write-front: Step 0 : FROM dockerfile/java:oracle-java8
sales-write-front: Pulling repository dockerfile/java
sales-write-front: Error: image dockerfile/java:oracle-java8 not found

After running vagrant up within e2e-tests (I am using docker base image "java:8"), all of the docker containers seem up and running (docker ps output is below):

CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a8d3941f4ed1        b58a56b01dae              "bin/sales-read-front"   43 hours ago        Up 43 hours                                                          sales-read-front
e7c034d15fce        204657a2ba9b              "bin/shipping-read-fr"   43 hours ago        Up 43 hours                                                          shipping-read-front
dfd562e6de9c        70423819a0af              "bin/invoicing-write-"   43 hours ago        Up 43 hours                                                          invoicing-write-front
cbc396460f6c        be183a4cc3a5              "bin/shipping-write-b"   43 hours ago        Up 43 hours                                                          shipping-write-back
c90bfd1fd860        70f68e8bbc05              "bin/sales-read-back"    43 hours ago        Up 43 hours                                                          sales-read-back
29b5ff787b1e        33a8c8cb1b73              "bin/invoicing-write-"   43 hours ago        Up 43 hours                                                          invoicing-write-back
3ed380af5bea        987377b43cd5              "bin/sales-write-fron"   43 hours ago        Up 43 hours                                                          sales-write-front
60ab39b74d0f        20354a828076              "bin/shipping-read-ba"   43 hours ago        Up 43 hours                                                          shipping-read-back
6e6f81cda8af        3faa1e2dd9bf              "bin/sales-write-back"   43 hours ago        Up 43 hours                                                          sales-write-back
4c74a6833460        postgres                  "/docker-entrypoint.s"   43 hours ago        Up 43 hours         0.0.0.0:5432->5432/tcp                           ecommerce-view-store
85d43484328b        newion/eventstore:3.0.3   "/bin/sh -c './run-no"   43 hours ago        Up 43 hours         0.0.0.0:1113->1113/tcp, 0.0.0.0:2113->2113/tcp   ecommerce-eventstore

**Comment by pawelkaczor** [comment]
Please test with recent changes (Akka 2.4.0 support). Please reopen if problem still exists.
